1.Numpy stands for

A. Numpy can be used to perform a wide variety of mathematical operations on  arrays.It stands for Numercial python

2.The most important object defined
in Numpy is an N-dimensional array
type called?

A. It is called ndarray.It describes the collection of items of the same type.



3.What will be output for the following code?

In [3]:
import numpy as np

In [6]:
a = np.array([1, 2, 3], dtype =
complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [7]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
a = np.array([1, 2, 3], dtype ="float")
print(a)

[1. 2. 3.]


In [12]:
a =np.dtype("i4")
print(a)

int32


In [13]:
a = np.array([1, 2, 3,4,5], ndmin= 2)
print(a)

[[1 2 3 4 5]]


In [17]:
dt =np.dtype([("age",np.int8)])
a = np.array([(10,),(20,),(30,)],dtype = dt)
a["age"]

array([10, 20, 30], dtype=int8)

In [20]:
a=np.array([1,2,3,5,8])
b=np.array([0,3,4,2,1])
c=a+b
c=c*a
print("c values:",c)
print(c[2])

c values: [ 1 10 21 35 72]
21


In [21]:
a = np.array([1,2,3,5,8])
a = a + 1
print (a[1])

3


In [22]:
a = np.array([[1,2,3],[0,1,4]])
print (a.size)

6


In [93]:
a =np.array([1,2,3,5,8])
a
print("No.of dimensions :",a.ndim)
print("Shape of array:",a.size)
print("Size of array:",a.shape)
from scipy import stats
print("describe:",stats.describe(a))

No.of dimensions : 1
Shape of array: 5
Size of array: (5,)
describe: DescribeResult(nobs=5, minmax=(1, 8), mean=3.8, variance=7.7, skewness=0.6216348579624364, kurtosis=-0.9675324675324677)


In [38]:
a = np.array([[1,2,3],[0,1,4]])
b = np.zeros((2,3), dtype=np.int16)
c = np.ones((2,3), dtype=np.int16)
d = a + b + c
print(d)

[[2 3 4]
 [1 2 5]]


In [88]:
print (d[1,2])
print (d.size)
print(np.ndim(d))
print(np.zeros((a)))

5
6
2
[[[[[0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0. 0. 0. 0.]]]]]


4.You have a matrix defined as
below:

In [52]:
A = np.array([[6, 1, 1],[4, -2, 5],[2, 8, 7]])
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [56]:
print("\nWith np.transpose(a) function")
print(np.transpose(A))
print("\nTrace:", A.trace())


With np.transpose(a) function
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]

Trace: 11


In [57]:
rank = np.linalg.matrix_rank(A)
print("\nRank:", rank)


Rank: 3


In [61]:
det = np.linalg.det(A)
print("\nDeterminant:", np.round(det))


Determinant: -306.0


In [63]:
inv = np.linalg.inv(A)
print("inverse of matrix:",inv)

inverse of matrix: [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


5.Type these lines of code and check
the output for each of them.

In [104]:
list1 =[1, 2, 3, 4 ,5, 6]
list2 =[10, 9, 8, 7, 6, 5]

In [106]:
print(list1 *list2)
print(list1+list2)
print(list1%list2)
print(list1/list2)
print(list1-list2)
print(list1^list2)

TypeError: ignored

6.Type these lines of code and check the output for each of them.

In [100]:
list1 = np.array([1, 2, 3, 4 ,5, 6])
list2 = np.array([10, 9, 8, 7, 6, 5])

In [103]:
print("Multiplication of array:",list1*list2)
print("Addition of array:",list1+list2)
print("percentage of array:",list1%list2)
print("Division of array:",list1/list2)
print("Subtract of array:",list1-list2)
print("Bitwise XOR:",list1^list2)

Multiplication of array: [10 18 24 28 30 30]
Addition of array: [11 11 11 11 11 11]
percentage of array: [1 2 3 4 5 1]
Division of array: [0.1        0.22222222 0.375      0.57142857 0.83333333 1.2       ]
Subtract of array: [-9 -7 -5 -3 -1  1]
Bitwise XOR: [11 11 11  3  3  3]
